### DISCUSSION TITLE
Usage with local database

### DISCUSSION THREAD

**Discussion by shawnmclean** [t3-oss/create-t3-turbo#1121] [Q&A]
I have this working locally and in production, pointing to a supabase production db. Everything works fine.

Now I want to do local db, and I pulled the db image from supabase. The migration works, however, when running nextjs, it is not communicating with the db.

Getting this error:

```
VercelPostgresError: VercelPostgresError - 'invalid_connection_string': This connection string is meant to be used with a direct connect
│ ion. Make sure to use a pooled connection string or try `createClient()` instead.
```

With a conn string of:

```
POSTGRES_URL="postgresql://postgres:postgres@127.0.0.1:5432/postgres"
```

Note: localhost didn't work, a nonsensical error was thrown that talks about websockets.

the docker-compose.yml:
```
version: "3.8"

services:
  db:
    image: supabase/postgres:15.1.1.61
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

```

Anyone able to get a local workflow going?

**Comment by noxify** [comment]
Yes~, will provide my config when I'm back home.~

Here our docker-compose.yaml

```yaml
name: local_stack
services:
  backend:
    container_name: "backend"
    env_file:
      - .env.docker
    environment:
      - BACKEND_PORT=4000
      - RDS_HOST=postgres
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
      args:
        - CI=1
        - PROJECT=backend
    restart: always
    ports:
      - 4000:4000
    networks:
      - docker_network
    depends_on:
      - postgres

  frontend:
    container_name: "frontend"
    env_file:
      - .env.docker
    environment:
      - RDS_HOST=postgres
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      args:
        - CI=1
        - PROJECT=frontend
    restart: always
    ports:
      - 3000:8080
    networks:
      - docker_network
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local_database
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - docker_network

networks:
  docker_network:

```

We're using a dedicated `.env` file for the docker deployment.

Here the relevant part for the RDS / DB variables:

```env
# Database
RDS_ENGINE="postgres"
RDS_HOST="postgres"
RDS_PORT=5432
RDS_USERNAME="postgres"
RDS_PASSWORD="postgres"
RDS_DBNAME="local_database"
RDS_DEBUG=false
RDS_URL=${RDS_ENGINE}://${RDS_USERNAME}:${RDS_PASSWORD}@postgres:${RDS_PORT}/${RDS_DBNAME}
```

Why not using the default `.env`?
We had some problems with overwriting the `RDS_HOST` via the container envs - It was easier for us to create a new env, instead of spending time to check why the `RDS_HOST` isn't overwritten.

Our Dockerfile is based on this howto:
https://fintlabs.medium.com/optimized-multi-stage-docker-builds-with-turborepo-and-pnpm-for-nodejs-microservices-in-a-monorepo-c686fdcf051f

We just modified the Dockerfile to make it work
* in our enterprise network ( using a local artifactory )
* Some customization which were required, because we're using prisma as ORM ( just calling the `generate` command and setting the  binary mirror to an allowed s3 endpoint

Hope this helps you.
