### DISCUSSION TITLE
Deploying trigger.dev project using GitHub Action

### DISCUSSION THREAD

**Discussion by j-fdion** [t3-oss/create-t3-turbo#1245] [Q&A] [answered]
[https://trigger.dev/docs/github-actions](url)

Hi!

I created a package named 'trigger' under the packages directory.

I was looking at their doc to deploy my trigger.dev project using GitHub Action. But I'm not really familiar with github actions and I'm not sure how I can edit the github action file to use a pnpm/monorepo setup.

Anybody has done this before and would care to share with me their solutions.

Thanks :)

**Comment by j-fdion** [comment, marked as answer]
Here's a working solution:

```

    trigger:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: Setup
          uses: ./tooling/github/setup
  
        - name: Deploy Trigger.dev
          working-directory: ./packages/trigger
          env:
            TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          run: pnpm dlx trigger.dev@latest deploy --env staging

```
