### ISSUE TITLE
bug: not working with local running postgres

### ISSUE THREAD

**Issue by princejoogie** [t3-oss/create-t3-turbo#1183]
### Provide environment information

```
System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M1
  Memory: 159.75 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.17.0 - ~/.local/state/fnm_multishells/28536_1726247644124/bin/node
  npm: 10.8.2 - ~/.local/state/fnm_multishells/28536_1726247644124/bin/npm
  pnpm: 9.7.1 - ~/.local/state/fnm_multishells/28536_1726247644124/bin/pnpm
  bun: 1.1.27 - /opt/homebrew/bin/bun
```

### Describe the bug

I wanted to run a local db for development so I created a `docker-compose.yml` to quickly spin up a postgres instance
```yml
services:
  postgres:
    image: postgres
    container_name: bazaarkit
    environment:
      POSTGRES_DB: bazaar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "2345:5432"

volumes:
  postgres_data:
```

then I have my `.env` point to this local db
```bash
POSTGRES_URL="postgres://postgres:postgres@localhost:2345/bazaar"
```

### Link to reproduction

https://github.com/princejoogie/t3-turbo-local-postgres-reproduction

### To reproduce

```
git clone https://github.com/princejoogie/t3-turbo-local-postgres-reproduction.git
pnpm i

cp .env.example .env # fill in discord oauth fields

docker compose up # run the local db
pnpm run db:push

pnpm run dev
```
