### ISSUE TITLE
feat: enable nextjs cache on github actions

### ISSUE THREAD

**Issue by kDaycares** [t3-oss/create-t3-turbo#350]
### Describe the feature you'd like to request

I'm not sure if this is intentional but nextjs builds are not being cached on GitHub actions:

I always see this:
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/131893469/236652124-ec49e4bb-edbe-47fe-9457-977021a3410d.png">

### Describe the solution you'd like to see

As described in nextjs docs [here:](https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions)
```yaml
uses: actions/cache@v3
with:
  # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
  path: |
    ~/.npm
    ${{ github.workspace }}/.next/cache
  # Generate a new cache whenever packages or source files change.
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
  # If source files changed but packages didn't, rebuild from a prior cache.
  restore-keys: |
    ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
```
But with `pnpm` implementation.
