### ISSUE TITLE
bug: next-env.d.ts is ignored and causes type errors in CI

### ISSUE THREAD

**Issue by MendyLanda** [t3-oss/create-t3-turbo#472]
Generally, image types are available through the `next-env.d.ts` file, generated by `nextjs` when running the `dev` command.

The problem arises because the `next-env.d.ts` file is listed in `.gitignore`. As a result, the CI's TypeScript server doesn't recognize the types of the images, causing the errors shown below.
<img width="1547" alt="failCi" src="https://github.com/t3-oss/create-t3-turbo/assets/54242706/53d1f4a1-6f21-4801-a748-d43d8c1d0f45">

Removing `next-env.d.ts` from `.gitignore` resolved the issue.

A year ago, @ijjk in `create-next-app` [decided to include](https://github.com/vercel/next.js/blame/fef6f82abafdad6c32a61ebbf4bff77f634bfc2d/packages/create-next-app/templates/default-tw/ts/gitignore#L35)  `next-env.d.ts` in `.gitignore`, but imo, it's unnecessary.

<details>
  <summary>Why is it unnecessary?</summary>
  
  Aside from the issue in CI, it can be confusing for a few seconds to minutes when you look at a fresh clone and don't understand why the types are wrong - until you run `dev`. 
  
  Here are some reasons to ignore this file:
  
  - It's generated automatically, so why include it? (we know why)
  - It sends a small signal that this file should not be edited (I guess? 🤷‍♂️)
  - If there are other reasons, please enlighten me
</details>

I'll submit a PR to remove the file from `.gitignore` if people agrees on this.

**Comment by juliusmarminge** [comment]
I noticed this a while ago on a different repo and solved that by adding `next-env.d.ts` to the `build.outputs` in `turbo.json`

**Comment by ahkhanjani** [comment]
@juliusmarminge This solution depends on the cache being used which makes typecheck depend on build, which isn't a requirement for typecheck. Clearing the cache will cause failure.

Would this not be a better solution:

```yml
typecheck:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: ./tooling/github/setup

    - name: Create next-env.d.ts
      run: echo '/// <reference types="next" />' > apps/nextjs/next-env.d.ts
      shell: bash

    - name: Typecheck
      run: pnpm typecheck
```

**Comment by ahkhanjani** [comment]
@juliusmarminge This solution depends on the cache being used which makes typecheck depend on build, which isn't a requirement for typecheck. Clearing the cache will cause failure.

Would this not be a better solution:

```yml
name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: "pnpm"

    - shell: bash
      run: pnpm add -g turbo

    - shell: bash
      run: pnpm install

    - shell: bash
      run: echo -e '/// <reference types="next" />\n/// <reference types="next/image-types/global" />' > apps/nextjs/next-env.d.ts
```
