### ISSUE TITLE
bug: create-turbo with npm or yarn is not working

### ISSUE THREAD

**Issue by dougrocha** [t3-oss/create-t3-turbo#544]
### Provide environment information

  System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M1
    Memory: 1.01 GB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.5.1 - ~/Library/Caches/fnm_multishells/36496_1692810355106/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/36496_1692810355106/bin/yarn
    npm: 9.8.0 - ~/Library/Caches/fnm_multishells/36496_1692810355106/bin/npm
    pnpm: 8.6.12 - /opt/homebrew/bin/pnpm

### Describe the bug

When making a new project with `npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo`. Selecting either npm or yarn as a package manager results in some errors down the line.

### NPM
npm install fails in the middle of create-turbo command. Fails due to it not being able to find certain types.

### YARN
Running yarn build or yarn dev results in next js failing and throwing an error.

The error says it is missing auto prefixer. Installing auto prefixer in `apps/nextjs` fixes this issue. But shouldnt be the end fix.

### PNPM
Works as expected with no errors out the box.

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### NPM
```
npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

# Select npm
# Will result in error

# Running will result in error as well
npm install
```
### YARN
```
npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

# Select yarn

# Environment Variables
# Fill out discord credentials with random text
cp .env.example .env

# Both of these result in the same error.
yarn build
# or
yarn dev
```

### Additional information

- NPM ERROR
```
~/dev 3s
❯ npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? temp
? Which package manager do you want to use? npm

Downloading files from repo https://github.com/t3-oss/create-t3-turbo. This might take a moment.

>>> Created a new Turborepo with the following:

apps
 - apps/expo
 - apps/nextjs
packages
 - packages/api
 - packages/auth
 - packages/db
tooling
 - tooling/eslint
 - tooling/prettier
 - tooling/tailwind
 - tooling/typescript

Installing packages. This might take a couple of minutes.

    Installing dependencies...
>>> npm install has failed.

~/dev 30s
❯ cd temp/

temp main
❯ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @acme/nextjs@0.1.0
npm ERR! Found: @tanstack/react-query@4.33.0
npm ERR! node_modules/@tanstack/react-query
npm ERR!   @tanstack/react-query@"^4.33.0" from @acme/nextjs@0.1.0
npm ERR!   apps/nextjs
npm ERR!     @acme/nextjs@0.1.0
npm ERR!     node_modules/@acme/nextjs
npm ERR!       workspace apps/nextjs from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @tanstack/react-query@"5.0.0-alpha.71" from @tanstack/react-query-next-experimental@5.0.0-alpha.80
npm ERR! node_modules/@tanstack/react-query-next-experimental
npm ERR!   @tanstack/react-query-next-experimental@"5.0.0-alpha.80" from @acme/nextjs@0.1.0
npm ERR!   apps/nextjs
npm ERR!     @acme/nextjs@0.1.0
npm ERR!     node_modules/@acme/nextjs
npm ERR!       workspace apps/nextjs from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/douglasrocha/.npm/_logs/2023-08-23T18_08_04_466Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/douglasrocha/.npm/_logs/2023-08-23T18_08_04_466Z-debug-0.log
```
- YARN ERROR
```
~/dev 2s
❯ npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

>>> TURBOREPO

>>> Welcome to Turborepo! Let's get you set up with a new codebase.

? Where would you like to create your turborepo? temp
? Which package manager do you want to use? yarn

Downloading files from repo https://github.com/t3-oss/create-t3-turbo. This might take a moment.

>>> Created a new Turborepo with the following:

apps
 - apps/expo
 - apps/nextjs
packages
 - packages/api
 - packages/auth
 - packages/db
tooling
 - tooling/eslint
 - tooling/prettier
 - tooling/tailwind
 - tooling/typescript

Installing packages. This might take a couple of minutes.

>>> Success! Created a new Turborepo at "temp".
Inside that directory, you can run several commands:

  yarn run build
     Build all apps and packages

  yarn run dev
     Develop all apps and packages

  yarn run lint
     Lint all apps and packages

Turborepo will cache locally by default. For an additional
speed boost, enable Remote Caching with Vercel by
entering the following command:

  npx turbo login

We suggest that you begin by typing:

  cd temp
  npx turbo login


~/dev 36s
❯ cd temp

temp main*
❯ cp .env.example .env

temp main*
❯ yarn build
yarn run v1.22.19
$ turbo build
• Packages in scope: @acme/api, @acme/auth, @acme/db, @acme/eslint-config, @acme/expo, @acme/nextjs, @acme/prettier-config, @acme/tailwind-config, @acme/tsconfig
• Running build in 9 packages
• Remote caching disabled
@acme/nextjs:build: cache miss, executing 15ead44adb102946
@acme/nextjs:build: $ pnpm with-env next build
@acme/nextjs:build:
@acme/nextjs:build: > @acme/nextjs@0.1.0 with-env /Users/douglasrocha/Dev/temp/apps/nextjs
@acme/nextjs:build: > dotenv -e ../../.env -- "next" "build"
@acme/nextjs:build:
@acme/nextjs:build: - info Creating an optimized production build...
@acme/nextjs:build: Failed to compile.
@acme/nextjs:build:
@acme/nextjs:build: src/app/layout.tsx
@acme/nextjs:build: An error occured in `next/font`.
@acme/nextjs:build:
@acme/nextjs:build: Error: Cannot find module 'autoprefixer'
@acme/nextjs:build: Require stack:
@acme/nextjs:build: - /Users/douglasrocha/Dev/temp/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js
@acme/nextjs:build: - /Users/douglasrocha/Dev/temp/node_modules/next/dist/build/webpack/config/blocks/css/index.js
@acme/nextjs:build: - /Users/douglasrocha/Dev/temp/node_modules/next/dist/build/webpack/config/index.js
@acme/nextjs:build: - /Users/douglasrocha/Dev/temp/node_modules/next/dist/build/webpack-config.js
@acme/nextjs:build: - /Users/douglasrocha/Dev/temp/node_modules/next/dist/build/webpack-build/impl.js
@acme/nextjs:build: - /Users/douglasrocha/Dev/temp/node_modules/next/dist/build/webpack-build/index.js
@acme/nextjs:build: - /Users/douglasrocha/Dev/temp/node_modules/next/dist/build/index.js
@acme/nextjs:build: - /Users/douglasrocha/Dev/temp/node_modules/next/dist/cli/next-build.js
@acme/nextjs:build: - /Users/douglasrocha/Dev/temp/node_modules/next/dist/lib/commands.js
@acme/nextjs:build: - /Users/douglasrocha/Dev/temp/node_modules/next/dist/bin/next
@acme/nextjs:build:     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
@acme/nextjs:build:     at /Users/douglasrocha/Dev/temp/node_modules/next/dist/server/require-hook.js:110:36
@acme/nextjs:build:     at Function.resolve (node:internal/modules/cjs/helpers:127:19)
@acme/nextjs:build:     at loadPlugin (/Users/douglasrocha/Dev/temp/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:54:32)
@acme/nextjs:build:     at /Users/douglasrocha/Dev/temp/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:162:56
@acme/nextjs:build:     at Array.map (<anonymous>)
@acme/nextjs:build:     at getPostCssPlugins (/Users/douglasrocha/Dev/temp/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:162:47)
@acme/nextjs:build:     at async /Users/douglasrocha/Dev/temp/node_modules/next/dist/build/webpack/config/blocks/css/index.js:124:36
@acme/nextjs:build:     at async /Users/douglasrocha/Dev/temp/node_modules/next/dist/build/webpack/loaders/next-font-loader/index.js:86:34
@acme/nextjs:build:     at async Span.traceAsyncFn (/Users/douglasrocha/Dev/temp/node_modules/next/dist/trace/trace.js:105:20)
@acme/nextjs:build:
@acme/nextjs:build:
@acme/nextjs:build: > Build failed because of webpack errors
@acme/nextjs:build:  ELIFECYCLE  Command failed with exit code 1.
@acme/nextjs:build: error Command failed with exit code 1.
@acme/nextjs:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@acme/nextjs:build: ERROR: command finished with error: command (/Users/douglasrocha/Dev/temp/apps/nextjs) yarn run build exited (1)
@acme/nextjs#build: command (/Users/douglasrocha/Dev/temp/apps/nextjs) yarn run build exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    7.22s
Failed:    @acme/nextjs#build

 ERROR  run failed: command  exited (1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by juliusmarminge** [comment]
This repo uses pnpm and it's not expected you can port it to other package managers without any modifications

**Comment by avarayr** [comment]
Can confirm this happens because I didn't notice repo docs telling me to use pnpm
Solution: use pnpm when asked.

**Comment by christo8989** [comment]
I'll add some changes that I made to move from pnpm to yarn and I hope it helps.

**.github/workflows/ci.yml**

```yml
name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup yarn
        uses: mskelton/setup-yarn@v1

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get yarn store directory
        id: yarn-cache
        run: |
          echo "yarn_cache_dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Setup yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.yarn_cache_dir }}
          key: ${{ runner.os }}-yarn-store-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-store-

      - name: Install deps (with cache)
        run: yarn install

      - name: lint and type-check
        run: yarn turbo lint format typecheck

      - name: Check workspaces
        run: yarn manypkg check
```

- Search for script definitions that have `pnpm` and replace it with `yarn`.
- Search and replace `pnpm-lock.yaml` with `yarn.lock`
